version: '3'

services:
  web:
    build: 
      context: .
      args:
        PHP_IMAGE: ${PHP_IMAGE:-php:7.4-apache}
    container_name: xampp_web
    volumes:
      - ./src:/var/www/html
      - ./apache_config:/etc/apache2/sites-enabled
    ports:
      - "8080:80"
    networks:
      - xampp_network
    depends_on:
      - db

  db:
    image: ${MARIADB_IMAGE:-mariadb:11.2}
    container_name: xampp_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - xampp_network

  phpmyadmin:
    image: ${PHPMYADMIN_IMAGE:-phpmyadmin/phpmyadmin}
    container_name: xampp_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    networks:
      - xampp_network
    depends_on:
      - db

networks:
  xampp_network: